"""empty message

Revision ID: b1f8688540d6
Revises: 
Create Date: 2024-04-16 17:57:57.729679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f8688540d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petfinder_id', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('declawed', sa.String(), nullable=True),
    sa.Column('house_trained', sa.String(), nullable=True),
    sa.Column('shots', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('spayed_neutered', sa.String(), nullable=True),
    sa.Column('special_needs', sa.String(), nullable=True),
    sa.Column('primary_breed', sa.String(), nullable=True),
    sa.Column('coat', sa.String(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('contact_address_city', sa.String(), nullable=True),
    sa.Column('contact_address_state', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('good_with_cats', sa.String(), nullable=True),
    sa.Column('good_with_children', sa.String(), nullable=True),
    sa.Column('good_with_dogs', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('foster_listing_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('preference', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_animal_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('petfinder_id', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('declawed', sa.String(), nullable=True),
    sa.Column('house_trained', sa.String(), nullable=True),
    sa.Column('shots', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('spayed_neutered', sa.String(), nullable=True),
    sa.Column('special_needs', sa.String(), nullable=True),
    sa.Column('primary_breed', sa.String(), nullable=True),
    sa.Column('coat', sa.String(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('contact_address_city', sa.String(), nullable=True),
    sa.Column('contact_address_state', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('good_with_cats', sa.String(), nullable=True),
    sa.Column('good_with_children', sa.String(), nullable=True),
    sa.Column('good_with_dogs', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('petfinder_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_animal_table')
    op.drop_table('foster_listing_table')
    op.drop_table('profile_table')
    op.drop_table('animal_table')
    # ### end Alembic commands ###
